##################################################################
#                       IMAGE DOCKER Comments                    #
# basé sur l'image node:alpine avec installation des dépendances #
#         " docker image build -t react-comments . "             #
##################################################################
FROM node:alpine
COPY . .
RUN npm install
CMD ["npm", "start"]