##################################################################
#                    IMAGE DOCKER Moderation                     #
# basé sur l'image node:alpine avec installation des dépendances #
#       " docker image build -t react-moderation . "             #
##################################################################
FROM node:alpine
COPY . .
RUN npm install
CMD ["npm", "start"]